kubernetes/cluster-registry

cmd/clusterregistry/app/cluster.go
cmd/clusterregistry/app/server.go

Rename cmd/cr/app/clusterregistry.go to cluster.go

---

pkg/crinit/init/init.go
pkg/crinit/init/init_test.go
pkg/crinit/util/util.go

This does not add full test coverage for crinit, but it moves away from a monolithic test and starts implementing method-level tests. The intention is to add an integration test for the whole crinit flow, and test the intricacies of the logic in unit tests.
cc @madhusudancs, @font

Modify the crinit unit tests and crinit to support more fine-grained unit tests.

---

README.md
docs/api_design.md
docs/development.md

I added a little bit of content, but the main intention here is to get a bit more structure and move content out of the top-level README.
cc @font, @pmorie, @madhusudancs

Add a docs directory, and reorganize the docs a bit

---

hack/update-codegen.sh
pkg/apis/clusterregistry/v1alpha1/doc.go

Also tweaks some cosmetic issues which should make the script a bit easier to follow, and adds the comment necessary to generate conversions.

Update the codegen scripts in repsonse to comments on #35.

---

pkg/crinit/init/init_test.go

Fix a few issues identified by go vet

---

pkg/apis/clusterregistry/types.go
pkg/apis/clusterregistry/v1alpha1/types.go

This is intended to get the API very close to an alpha state.
cf #20 
cc @font @madhusudancs @pmorie

Update the cluster API per the latest decisions

---

pkg/crinit/crinit.go
pkg/crinit/util/util.go

@font @pmorie @ericchiang @madhusudancs

Tweak the setup of the crinit command to improve its usability

---

Gopkg.lock
Gopkg.toml
vendor/github.com/golang/glog/README
vendor/github.com/golang/glog/glog.go

Fixes #66.
/cc @madhusudancs 
fyi @font 

Update the glog dependency version to match the version used in Kubernetes

---

docs/development.md

Update development doc to include hg prerequisite

---

docs/README.md

Add docs/README

---

CONTRIBUTING.md

/cc @pmorie, @madhusudancs
@font

Add more details to CONTRIBUTING.md

---

cmd/clusterregistry/BUILD.bazel
docs/development.md
hack/release.sh

Addresses #102, though there's still some more clean-up work necessary to make the the user experience smooth.
/cc @font @pmorie @madhusudancs

Add a script that does a nightly build of the cluster registry.

---

README.md

Add a link to the nightly build in README.md

Add link to nightly build to README.md

---

hack/release.sh

This should fix the nightly build.
/cc @madhusudancs @font @pmorie

Update the release script to configure gcloud Docker credentials.

---

docs/userguide.md

Add a user guide for the cluster registry.

---

pkg/apis/clusterregistry/validation/validation.go
pkg/apis/clusterregistry/validation/validation_test.go

Add validation that metadata.clusterName is not set.

---

README.md

Add widgets and notes about package docs to the README

---

cmd/crinit/crinit.go
pkg/apis/clusterregistry/install/install.go
pkg/apis/clusterregistry/register.go
pkg/apis/clusterregistry/types.go
pkg/apis/clusterregistry/v1alpha1/doc.go
pkg/apis/clusterregistry/v1alpha1/register.go
pkg/apis/clusterregistry/v1alpha1/types.go
pkg/apis/clusterregistry/validation/validation.go
pkg/clusterregistry/authenticator/config.go
pkg/clusterregistry/doc.go
pkg/clusterregistry/options/authentication.go
pkg/clusterregistry/options/options.go
pkg/clusterregistry/options/validation.go
pkg/clusterregistry/testing/doc.go
pkg/crinit/aggregated/aggregated.go
pkg/crinit/crinit.go
pkg/crinit/standalone/standalone.go
pkg/crinit/standalone/standalone_test.go
pkg/crinit/util/util.go
pkg/registry/cluster/doc.go
pkg/registry/cluster/etcd/etcd.go
pkg/registry/cluster/etcd/registrytestutil/registrytestutil.go

/cc @font @pmorie @madhusudancs

Add some more documentation comments, and fix some lint errors

---

README.md
docs/README.md

Update to relative links and add userguide doc link

---

pkg/clusterregistry/testing/server_test.go

Add Update,Delete to cluster CRUD integration test

---

docs/development.md

From @madhusudancs's comment on #88. Also fixes a bad link.

Add a section about k8s-bot commands to the developer docs.

---

pkg/clusterregistry/BUILD.bazel
pkg/registry/cluster/BUILD.bazel

Update bazel BUILD files

---

api/swagger.json
pkg/apis/clusterregistry/v1alpha1/zz_generated.openapi.go

We'll want to add the `hack/verify-codegen.sh` and `hack/verify-openapi-spec.sh` scripts as a prow job.

Update OpenAPI generated code and spec

---

examples/samplecontainer/cluster-two.yaml
examples/samplecontainer/cluster.yaml

Add cloudProvider to example cluster configs

---

docs/README.md
docs/development.md
docs/release.md

/cc @pmorie @madhusudancs @font 
I plan to go through this process once #144 is in to create the 0.0.1 release, hopefully this afternoon or Monday morning.

Add a doc that explains (in brief) how to do a release.

---

RELEASE.md

/cc @pmorie @madhusudancs @font

Update RELEASE.md to point to docs/release.md

---

docs/release.md

A few changes to the release process following the v0.0.1 release.

Update release.md following the v0.0.1 release

---

hack/update-codegen.sh
hack/update-openapi-spec.sh

Install curl for use in prow job's k8s test image

---

api/swagger.json
hack/update-codegen.sh
pkg/apis/clusterregistry/v1alpha1/zz_generated.openapi.go

Fix for #159.
Thanks to @luksa for identifying a dependency issue!

Fix for #159

---

OWNERS

Add pmorie and font to the OWNERS file.

---

BUILD.bazel
Gopkg.lock
LICENSES
cmd/clusterregistry/BUILD.bazel
cmd/crinit/BUILD.bazel
hack/update-licenses.sh
hack/verify-licenses.sh

Also generates a `SOURCES.md` file that includes links to the relevant source archives on GitHub.
Fixes #74.

Add a script to update a LICENSES file, and include license info in the tarballs.

---

examples/webhook-authz/README.md
examples/webhook-authz/authz.yaml
pkg/clusterregistry/options/authorization.go

Follow-up to comments #155, along with a fix that should have gone into that PR.
/cc @madhusudancs @font @pmorie

Fixes for webhook authorization

---

README.md

/cc @pmorie @madhusudancs @font

Add a link to the GCS viewer for cluster registry releases.

---

docs/userguide.md

Add link to userguide to enable k8s aggregation layer

---

hack/verify-go-src.sh

Fixes #179.
Now that we're relying on a different test image for the Prow job that runs this script, we can remove the dependency on a temporary `GOPATH` setup. This is because the new image contains the Go toolchain and a proper GOPATH setup prior to launching this script.

Remove dependency on temporary GOPATH

---

Gopkg.lock
pkg/crinit/aggregated/BUILD.bazel
pkg/crinit/aggregated/aggregated_test.go
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/BUILD
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/doc.go
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/fake/register.go
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/BUILD
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/doc.go
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiregistration_client.go
vendor/k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset/typed/apiregistration/v1beta1/fake/fake_apiservice.go

Adds crinit aggregated unit tests similar to standalone_test.go. Follow up PR will attempt to refactor for common unit test for standalone and aggregated.
Addresses issue: #114 
/cc @perotinus @font

added crinit aggregated test

---

LICENSES

Update the LICENSES file.

---

api/swagger.json

Update the OpenAPI spec for v0.0.3

---

test/integration/doc.go
test/integration/server_test.go
test/integration/testserver.go

Update integration package name to match path

---

docs/README.md
docs/api-reference/clusterregistry/v1alpha1/definitions.html
docs/api-reference/clusterregistry/v1alpha1/operations.html
docs/api_reference.md
hack/update-api-reference-docs.sh

I plan to follow up with details on generating these docs in a future PR.
/cc @perotinus @madhusudancs @pmorie 

Add cluster-registry API reference docs

---

examples/samplecontainer/cluster-two.yaml
examples/samplecontainer/cluster.yaml

Update clientCIDR fields to match API definition

---

docs/userguide.md

Fix example for creating cluster

---

hack/update-api-reference-docs.sh

Use k8s GCR vanity URL

---

api/swagger.json

Update the OpenAPI spec for the v0.0.4 release.

---

docs/development.md

Highlight clone location.

---

cluster-registry-crd.yaml
docs/reference/openapi-spec/swagger.json
examples/cluster-two.yaml
examples/cluster.yaml
examples/slackcontroller/slackcontroller.go
pkg/apis/clusterregistry/v1alpha1/types.go
pkg/apis/clusterregistry/v1alpha1/zz_generated.kubebuilder.go
pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/cluster.go
pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/clusterregistry_client.go
pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/fake/fake_cluster.go
pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/fake/fake_clusterregistry_client.go
pkg/client/informers/externalversions/clusterregistry/v1alpha1/cluster.go
pkg/client/informers/externalversions/clusterregistry/v1alpha1/interface.go
pkg/client/listers/clusterregistry/v1alpha1/cluster.go
pkg/client/listers/clusterregistry/v1alpha1/expansion_generated.go
test/integration/server_test.go

/assign @font @madhusudancs @pmorie 
Fixes #81,  #82 and #228.

Add namespaces to the cluster CRD

---

docs/userguide.md

Fix the user guide to work for namespaced clusters.

---

SECURITY_CONTACTS

Does anyone else want to volunteer to be a security contact?
/assign @madhusudancs @pmorie @font

Add SECURITY_CONTACTS to the cluster registry repo

---

README.md

It's a bit confusing as written.

s/cluster API/Cluster Registry API/g

---

.bazelrc

Remove the unused .bazelrc file.

---

examples/slackcontroller/README.md

Minimal fix to a broken user guide link.
/assign @perotinus

Fix broken link to userguide

---

hack/go-tools/verify-gofmt.sh

Updated promopt message for gofmt.

---

docs/userguide.md
examples/cluster-two.yaml
examples/cluster.yaml

Added status to cluster yaml template.

---

docs/development.md

/cc @font @madhusudancs @perotinus @pmorie

Document crd-install annotation for cluster registry crd.

---

cluster-registry-crd.yaml
docs/development.md
docs/reference/build/index.html
docs/reference/openapi-spec/swagger.json
pkg/apis/clusterregistry/v1alpha1/zz_generated.kubebuilder.go
pkg/client/clientset/versioned/clientset.go
pkg/client/clientset/versioned/fake/clientset_generated.go
pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/fake/fake_cluster.go
pkg/client/informers/externalversions/factory.go

/cc @font @madhusudancs @perotinus @pmorie

Upgrade kubebuilder to 1.0.3.

---

examples/slackcontroller/slackcontroller.go

part of https://github.com/kubernetes-sigs/federation-v2/issues/381#issue-376377377

Switch to github.com/pkg/errors

---

examples/slackcontroller/main.go
examples/slackcontroller/slackcontroller.go

ref: https://github.com/kubernetes/kubernetes/issues/70264

Use a forked version of glog in kubernetes
