README.md
cmd/clusterregistry/BUILD.bazel

I started going through the README to build the binaries and container images and ran into some issues fixed here:
1. Update script name
1. Update build and run commands
1. Update bazel BUILD file to allow specifying `project` to upload container image
1. Update generated bazel BUILD file
1. Typos
I also ran into an issue because I was missing the Mercurial `hg` CLI tool due to a [bitbucket dependency for `bitbucket.org/ww/goautoneg`](https://github.com/kubernetes/apiserver/blob/b2a8ad67a002d27c8945573abb80b4be543f2a1f/Godeps/Godeps.json#L10) since we have [k8s.io/apiserver in our WORKSPACE dependency](https://github.com/kubernetes/cluster-registry/blob/94f78f21436ae2a8b24ca0fb8d07001c5b7cd52d/WORKSPACE#L61-L67). Installing Mercurial fixed the problem but I'm thinking that should have …

Update README instructions and bazel BUILD file

---

README.md
WORKSPACE

Tested by removing the hg command from the PATH and running `bazel fetch`.

 Remove the need for Mercurial to be installed by depending on an HTTP archive instead.

---

WORKSPACE

Tested with bazel 0.6.0 and 0.5.4.

Update the versions of go and docker rules in the WORKSPACE.

---

cmd/clusterregistry/app/server.go

Without this, the API server will not authorize any requests.
cc @font @madhusudancs

Uncomment a block that configures the API server with authentication options.

---

pkg/apis/clusterregistry/types.go
pkg/apis/clusterregistry/v1alpha1/types.go

The API is still a WIP, but this brings it closer to the expected finalform, and to what exists in the API design document.
cf https://docs.google.com/document/d/1Oi9EO3Jwtp69obakl-9YpLkP764GZzsz95XJlX1a960/edit# (Must be member of [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) to view.)

Flesh out the API of the cluster registry

---

.gitignore
BUILD.bazel
hack/bazel-test.sh
hack/gopath_from_workspace.sh
hack/update-codegen.sh

Also, fix an(other) issue with update-codegen by explicitly setting the `--extra-peer-dirs` and ensuring that they are fetched before the generation command is run.
cc @madhusudancs @font

Add a script that can be used to run CI jobs for bazel

---

docs/development.md

I ran into a python error when trying to push to GCR without docker-credential-gcr installed. I propose that it be added to the prerequisites.
Another potential addition is `go get apimachinery` which I did not have installed prior to attempting to build cluster registry and caused my build to fail. I still am not sure what apimachinery is/does and why it would/wouldn't be installed anyway. I am happy to add this to the prerequisites too if it makes sense.

docker-credential-gcr needed for push to GCR

---

WORKSPACE
pkg/clusterregistry/options/options.go
pkg/clusterregistry/server.go
pkg/registry/cluster/etcd/etcd.go
pkg/registry/cluster/registry.go

This is a first step towards checked-in vendored dependencies.
- Update the Go rules to use the same version as used by `k/k`
- Update the `k/` dependencies to post-1.8 versions.
The versions used here were generally those pulled by the `dep` tool, which I have been using for vendoring. A future PR will replace the `WORKSPACE` dependencies with a vendor tree.
/assign @madhusudancs, @pmorie 
cc @font

Update the cluster-registry dependencies to newer versions.

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

We can add more content to these later, but for now this is a low-tech way to make sure that issues and PRs are (usually) labelled `sig/multicluster`.
/cc @madhusudancs

Add issue and PR templates to the cluster registry.

---

pkg/clusterregistry/options/options.go
pkg/clusterregistry/options/validation.go
pkg/clusterregistry/server.go
pkg/clusterregistry/testing/BUILD.bazel
pkg/clusterregistry/testing/server_test.go
pkg/clusterregistry/testing/testserver.go

This is based on work done for the kube-apiserver in [k/k/46865](https://github.com/kubernetes/kubernetes/pull/46865).

 Add a basic integration test for the cluster registry

---

.bazelrc
cmd/clusterregistry/BUILD.bazel
cmd/clusterregistry/clusterregistry.go
cmd/crinit/BUILD.bazel
docs/development.md
hack/print-workspace-status.sh
pkg/crinit/BUILD.bazel
pkg/crinit/crinit.go
pkg/crinit/standalone/BUILD.bazel
pkg/version/BUILD.bazel
pkg/version/base.go
pkg/version/def.bzl
pkg/version/version.go

We can determine a better versioning/tagging strategy later. This is mostly pulled from k/k, with some simplifications. At the least, it gives us a way to track what versions of the tools people are using, which is a big win.
/cc @pmorie @madhusudancs @font

Stamp bazel-built binaries with version informaton

---

.gitignore
examples/samplecontainer/Dockerfile
examples/samplecontainer/README.md
examples/samplecontainer/cluster-two.yaml
examples/samplecontainer/cluster.yaml
examples/samplecontainer/contents/config
examples/samplecontainer/contents/cr-apiservice.yaml
examples/samplecontainer/contents/cr-service.yaml
examples/samplecontainer/contents/run.sh
examples/slackcontroller/BUILD.bazel
examples/slackcontroller/README.md
examples/slackcontroller/main.go
examples/slackcontroller/slackcontroller.go

These are a bit messy still, but they demonstrate a simple controller and how the cluster registry API server runs. We can iterate.
Addresses #108.

Add examples for the cluster registry

---

docs/userguide.md
pkg/crinit/aggregated/aggregated.go
pkg/crinit/crinit.go
pkg/crinit/standalone/standalone.go

Also adds a `--short` flag for the version.

Add init subcommands to the aggregated and standalone crinit commands.

---

cmd/clusterregistry/BUILD.bazel
cmd/crinit/BUILD.bazel
docs/development.md
hack/release.sh

Also moves to using `BUILD` rules to create tarballs, to simplify the script a bit.
/cc @font @madhusudancs @pmorie 
- changes the layout of the GCR repo, removing the `nightly` subpath. It seems fine to have all images in one directory, since they are all tagged
- there is no hard link between repo tags and the version passed to the release script. This should be fixed later with automation

Update the release script to support versioned releases.

---

docs/userguide.md
examples/webhook-authz/README.md
examples/webhook-authz/authz.yaml
examples/webhook-authz/rules.hcl
examples/webhook-authz/webhook-config.yaml
pkg/clusterregistry/options/BUILD.bazel
pkg/clusterregistry/options/authorization.go

Also adds an example using a webhook for authorization.
Fixes #46.
/cc @font @pmorie @madhusudancs

Implement standalone webhook authoritzation.

---

cmd/crinit/crinit.go

Change the default clusterregistry image deployed by crinit

---

docs/development.md
hack/go-tools/verify-gofmt.sh
hack/go-tools/verify-govet.sh
hack/verify-go-src.sh
pkg/crinit/aggregated/aggregated.go
pkg/crinit/standalone/standalone_test.go

Adding scripts from [repo-infra](https://github.com/kubernetes/repo-infra/tree/0aafaab9e158d3628804242c6a9c4dd3eb8bce1f/verify) to help verify go source code. It would be best to vendor in the scripts to execute them directly, but we are blocked on https://github.com/golang/dep/issues/1306.
The first commit adds the scripts and the second commit fixes the errors.
This can be followed up with a prow job.

Add repo-infra scripts to verify go source code

---

api/swagger.json
docs/development.md
hack/go-tools/verify-gofmt.sh
hack/go-tools/verify-govet.sh
hack/verify-go-src.sh
pkg/crinit/aggregated/aggregated.go
pkg/crinit/common/common.go
pkg/crinit/options/options.go
pkg/crinit/standalone/standalone.go
pkg/crinit/standalone/standalone_test.go
pkg/crinit/util/util.go

- Update OpenAPI spec after cluster registry v0.0.2 released.
- Updated the script that runs all Go source file verify scripts to not take any arguments. This helps simplify it, easier to document it, and easier to run as a Prow job.
- Also updated individual verify scripts to allow being run from any directory.
- Fixed the `gofmt` errors.

Update and simplify Go source file verification scripts

---

pkg/clusterregistry/authenticator/config.go
pkg/clusterregistry/options/authentication.go

I don't think there's a need for this for the cluster registry, considering it's not actually trying to bootstrap nodes into a cluster. If there is in the future, it's easier to add it back.

Remove the bootstrap token logic from the cluster registry.

---

pkg/crinit/common/common.go

This went into v0.0.2 with the recent `crinit` refactor, so we'll need to release v0.0.3.

Fix crinit standalone deployment

---

pkg/crinit/aggregated/BUILD.bazel
pkg/crinit/aggregated/aggregated.go
pkg/crinit/common/common.go
pkg/crinit/options/options.go

/cc @madhusudancs @pmorie @font 
Also, adds reasonable timeouts for the `Waiting for API server...` operations.
Addresses #118. Also filed #187 as a result of this work to think holistically about how to give troubleshooting help when `crinit` fails.

Improve crinit's handling of waiting for the cluster registry API server.

---

pkg/crinit/aggregated/aggregated.go

I discovered this when I attempted to create a new `ClusterRoleBinding` referencing this `ClusterRole`. Until I changed from `cluster` to `clusters`, it didn't work.
Before:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
labels:
app: clusterregistry
name: clusterregistry.k8s.io:apiserver
rules:
- apiGroups:
- clusterregistry.k8s.io
resources:
- cluster
verbs:
- get
- list
- watch
- create
- update
- patch
- delete
```
After (only change is `clusters` under `resources`):
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
labels:
app: clusterregistry
name: clusterregistry.k8s.io:apiserver
rules:
- apiGroups:
- clusterregistry.k8s.io
resources:
- clusters
verbs:
- get
- list
- watch
- create
- update
- patch
- delete
```
This brings up …

Fix clusterregistry.k8s.io:apiserver ClusterRole

---

docs/development.md

Typo: fix boostrap->bootstrap

---

pkg/crinit/aggregated/aggregated.go
pkg/crinit/aggregated/delete.go
pkg/crinit/aggregated/init.go

Remove unnecessary cluster role and cluster role binding objects as I don't think we'll need it. This is mainly used to provide permissions for controllers within the cluster to perform specific cluster operations e.g. an admission controller to perform specific cluster resource operations. This cleans up and simplifies the code a bit. We can always add it back later if needed.
The [k8s docs on this](https://kubernetes.io/docs/tasks/access-kubernetes-api/setup-extension-api-server/) are a little misleading and suggest this is needed.

Remove cluster role and binding for clusters

---

pkg/crinit/aggregated/aggregated_test.go

This is a follow up PR to #170 which adds validation of the contents of the RBAC Object in the crinit aggregated test
Hopefully closes issue: #114
If it doesn't, please let me know what else needs to be done to satisfy this issue and I can work on it.

validates contents contained in createdRBACObj in aggregated test

---

cluster-registry-crd.yaml
docs/development.md

- leave all the generated fields in the YAML, to make the process of generating and updating simpler
- fix a bug with the generated YAML. https://github.com/kubernetes-sigs/kubebuilder/issues/220 tracks fixing this issue upstream.
/assign @pmorie @madhusudancs @font

Some small updates to the cluster CRD YAML

---

docs/userguide.md

fix crd yaml path in website, previously was 404

---

cluster-registry-crd.yaml
pkg/apis/clusterregistry/v1alpha1/types.go
pkg/apis/clusterregistry/v1alpha1/zz_generated.kubebuilder.go

The Cluster's Status field was missing the 'omitempty' tag, which caused
the generation machinery to mark it as required. It should be optional.
/cc @madhusudancs @font @pmorie 

Fix a missing 'omitempty' tag.

---

docs/reference/build/README.md
docs/reference/build/scroll.js
hack/imports.go

Signed-off-by: mooncake <xcoder@tenxcloud.com>
Fix typos in below files:
1. docs/reference/build/README.md
2. docs/reference/build/scroll.js
3. hack/imports.go

Fix typos in the files

---

docs/reference/build/README.md

Fix typos: prefered->preferred, depedencies->dependencies

Fix typos: prefered->preferred, depedencies->dependencies
